version: '3'

services:
  web:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
    restart: unless-stopped
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/.env
    environment:
      - PGHOST=db
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - ./db/init/init-schema.sql:/docker-entrypoint-initdb.d/01-init-schema.sql
      - ./db/init/init-data.sql:/docker-entrypoint-initdb.d/02-init-data.sql
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    restart: unless-stopped

  proxy:
    image: nginx:1-alpine
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web
      - api


