version: '3'

services:
  web:
    stdin_open: true
    build:
      dockerfile: dev.Dockerfile
      context: ./web
    command: test
    volumes:
      - /app/node_modules
      - ./web:/app
    depends_on:
      - api

  api:
    build: ./api
    command: test
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/.env
    environment:
      - PGHOST=db


